---
title: "Lab 3"
author: "Michelle Hernandez"
format:
  html:
    embed-resources: true
---

## 1. read in the data

```{r}
download.file(
  "https://raw.githubusercontent.com/USCbiostats/data-science-data/master/02_met/met_all.gz",
  destfile = "met_all.gz",
  method   = "libcurl",
  timeout  = 60
)

met <- data.table::fread("met_all.gz")

```

## 2. Check dimensions headers footers. How many columns?

```{r}
dim(met)
#There are 2377343 and 30 columns in the met dataset
head(met)
tail(met)

```

There are 2377343 and 30 columns in the met dataset

## 3. Look at the variables

```{r}
str(met)

```

## 4. Take a closer look

```{r}
table(met$year)
table(met$day)
table(met$hour)

summary(met$temp)
summary(met$elev)
summary(met$wind.sp)

met[met$elev==9999.0] <- NA
summary(met$elev)

met <- met[temp>-40]
met2 <- met[order(temp)]
head(met2)

```

## 5. Check data against source

```{r}
met[met$temp==-17.2,]
# yoder colorado, prob doesnt get that cold so we should remove

met <- met[temp>-15]
met2 <- met[order(temp)]
head(met2)
summary(met$temp)
# We removed any entries with a temp > -15, our lowest temp is now -3C which is reasonable

```

## 6. Calculate summary stats

```{r}
eleview <- met[elev==max(elev), ]
summary(eleview)

cor(eleview$temp, eleview$wind.sp, use="complete")
cor(eleview$temp, eleview$hour, use="complete")
cor(eleview$wind.sp, eleview$day, use="complete")
cor(eleview$wind.sp, eleview$hour, use="complete")
cor(eleview$temp, eleview$day, use="complete")

```

## 7. Graphs

```{r}

library(dplyr) 
library(magrittr)
library(leaflet)
library(devtools)
library(R.utils)
```

```{r}

hist(met$elev, breaks=100)
hist(met$temp)
hist(met$wind.sp, breaks=100)

leaflet(eleview) %>%
  addProviderTiles('OpenStreetMap') %>% 
  addCircles(lat=~lat,lng=~lon, opacity=1, fillOpacity=1, radius=100)

library(lubridate)
eleview$date <- with(eleview, ymd_h(paste(year, month, day, hour, sep= ' ')))
summary(eleview$date)

eleview <- eleview[order(date)]
head(eleview)

plot(eleview$date, eleview$temp, type='l')

plot(eleview$date, eleview$wind.sp, type='l')

```

## 8. Ask questions

What is the distribution of wind direction?

```{r}
library(tidyverse)
library(data.table)
ggplot(met, aes(x = wind.dir)) +
  geom_bar(aes(y = ..count..), fill = "blue", bins = 36) +
  coord_polar(start = 0) +
  labs(title = "Wind Direction Distribution")

```

what is the distribution of wind speeds?

```{r}
ggplot(met, aes(x = wind.sp)) +
  geom_histogram(binwidth = 1, fill = "green") +
  labs(title = "Wind Speed Distribution")

```

```{r}
barplot(met$wind.sp)

```

is wind speed association with temperature?

```{r}
model <- lm(met$wind.sp~ met$temp, data = met)
model

summary(model)
plot(model)
```
